version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/enertec
hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      runas: root
  AfterInstall:
    - location: scripts/afterInstall.sh
      runas: root
