<?php

return [
    'variables' => [
        ['id' => 1, 'display_name' => 'Energia activa(kWh)', 'icon' => 'fas fa-tachometer-alt', 'variable_name' => 'import_wh', 'chart_type' => 'line', 'real_time' => true, 'style' => 'active_energy'],
        ['id' => 2, 'display_name' => 'Horario(kWh)', 'icon' => 'fas fa-tachometer-alt', 'variable_name' => 'import_wh', 'chart_type' => 'column', 'real_time' => false, 'style' => 'active_energy'],
        ['id' => 3, 'display_name' => 'Acumulado fases(kWh)', 'icon' => 'fas fa-tachometer-alt', 'variable_name' => 'phase_import_kwh', 'chart_type' => 'line', 'real_time' => true, 'style' => 'active_energy'],
        ['id' => 4, 'display_name' => 'Horario fases(kWh)', 'icon' => 'fas fa-tachometer-alt', 'variable_name' => 'phase_import_kwh', 'chart_type' => 'column', 'real_time' => false, 'style' => 'active_energy'],

        ['id' => 5, 'display_name' => 'Energia reactiva(kVARh)', 'icon' => 'fas fa-atom', 'variable_name' => 'import_VArh', 'chart_type' => 'line', 'real_time' => true, 'style' => 'reactive_energy'],
        ['id' => 6, 'display_name' => 'Horario(kVARh)', 'icon' => 'fas fa-atom', 'variable_name' => 'import_wh', 'chart_type' => 'column', 'real_time' => false, 'style' => 'reactive_energy'],
        ['id' => 7, 'display_name' => 'Acumulado fases (kVARh)', 'icon' => 'fas fa-atom', 'variable_name' => 'phase_import_kvarh', 'chart_type' => 'line', 'real_time' => true, 'style' => 'reactive_energy'],
        ['id' => 8, 'display_name' => 'Horario fases (kVARh)', 'icon' => 'fas fa-atom', 'variable_name' => 'phase_import_kvarh', 'chart_type' => 'column', 'real_time' => false, 'style' => 'reactive_energy'],

        ['id' => 9, 'display_name' => 'Reactiva Capacitiva(kVARCh)', 'icon' => "fa-brands fa-creative-commons-nd", 'variable_name' => 'phase_import_kvarh', 'chart_type' => 'line', 'real_time' => false, 'style' => 'reactive_capacitive'],
        ['id' => 10, 'display_name' => 'Horario (kVARCh)', 'icon' => 'fa-brands fa-creative-commons-nd', 'variable_name' => 'import_VArh', 'chart_type' => 'column', 'real_time' => false, 'style' => 'reactive_capacitive'],
        ['id' => 11, 'display_name' => 'Acumulado fases (kVARCh)', 'icon' => 'fa-brands fa-creative-commons-nd', 'variable_name' => 'import_VArh', 'chart_type' => 'line', 'real_time' => false, 'style' => 'reactive_capacitive'],
        ['id' => 12, 'display_name' => 'Horario fases (kVARCh)', 'icon' => 'fa-brands fa-creative-commons-nd', 'variable_name' => 'import_VArh', 'chart_type' => 'column', 'real_time' => false, 'style' => 'reactive_capacitive'],

        ['id' => 13, 'display_name' => 'Reactiva Inductiva(kVARLh)', 'icon' => "fa-brands fa-creative-commons-sampling", 'variable_name' => 'phase_import_kvarh', 'chart_type' => 'line', 'real_time' => false, 'style' => 'reactive_inductive'],
        ['id' => 14, 'display_name' => 'Horario (kVARLh)', 'icon' => 'fa-brands fa-creative-commons-sampling', 'variable_name' => 'import_VArh', 'chart_type' => 'column', 'real_time' => false, 'style' => 'reactive_inductive'],
        ['id' => 15, 'display_name' => 'Acumulado fases (kVARLh)', 'icon' => 'fa-brands fa-creative-commons-sampling', 'variable_name' => 'import_VArh', 'chart_type' => 'line', 'real_time' => false, 'style' => 'reactive_inductive'],
        ['id' => 16, 'display_name' => 'Horario fases (kVARLh)', 'icon' => 'fa-brands fa-creative-commons-sampling', 'variable_name' => 'import_VArh', 'chart_type' => 'column', 'real_time' => false, 'style' => 'reactive_inductive'],


        ['id' => 17, 'display_name' => 'Voltaje(V)', 'icon' => 'fas fa-lightbulb', 'variable_name' => 'volt', 'chart_type' => 'line', 'real_time' => true, 'style' => 'voltage'],
        ['id' => 18, 'display_name' => 'Corriente(A)', 'icon' => 'fas fa-bolt', 'variable_name' => 'current', 'chart_type' => 'line', 'real_time' => true, 'style' => 'current'],
        ['id' => 19, 'display_name' => 'Potencia(W)', 'icon' => 'fas fa-long-arrow-alt-right', 'variable_name' => 'power', 'chart_type' => 'line', 'real_time' => true, 'style' => 'power'],
        ['id' => 20, 'display_name' => 'P. Aparente(VA)', 'icon' => 'fas fa-expand-alt', 'variable_name' => 'VA', 'chart_type' => 'line', 'real_time' => true, 'style' => 'power'],
        ['id' => 21, 'display_name' => 'P. Reactiva(VAR)', 'icon' => 'fas fa-long-arrow-alt-up', 'variable_name' => 'VAr', 'chart_type' => 'line', 'real_time' => true, 'style' => 'power'],
        ['id' => 22, 'display_name' => 'FP', 'icon' => 'fas fa-exchange-alt', 'variable_name' => 'power_factor', 'chart_type' => 'line', 'real_time' => true, 'style' => 'power_factor'],
        ['id' => 23, 'display_name' => 'Angulo fase', 'icon' => 'fas fa-greater-than-equal', 'variable_name' => 'phase_angle', 'chart_type' => 'line', 'real_time' => true, 'style' => 'phase_angle'],
        ['id' => 24, 'display_name' => 'Voltaje fases(V)', 'icon' => 'fas fa-code-branch', 'variable_name' => 'volts', 'chart_type' => 'line', 'real_time' => true, 'style' => 'voltage'],
        ['id' => 25, 'display_name' => 'THDI(%)', 'icon' => 'fas fa-hubspot', 'variable_name' => 'current_thd', 'chart_type' => 'line', 'real_time' => true, 'style' => 'thd'],
        ['id' => 26, 'display_name' => 'THDV(%)', 'icon' => 'fas fa-percentage', 'variable_name' => 'volt_thd', 'chart_type' => 'line', 'real_time' => true, 'style' => 'thd'],
        ['id' => 27, 'display_name' => 'THDV fases(%)', 'icon' => 'fas fa-percent', 'variable_name' => 'volts_thd', 'chart_type' => 'line', 'real_time' => true, 'style' => 'thd'],
        ['id' => 28, 'display_name' => 'Frecuencia(Hz)', 'icon' => 'fas fa-chart-line', 'variable_name' => 'frecuency', 'chart_type' => 'line', 'real_time' => true, 'style' => 'frecuency'],
    ],


    'data_frame' => [
        ['id' => 1, 'variable_name' => 'network_operator_id', 'description' => '', 'display_name' => '', 'variable_id' => '', 'key' => '', 'start' => 0, 'lenght' => 16, 'type' => 'Q', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 2, 'variable_name' => 'equipment_id', 'description' => '', 'display_name' => '', 'variable_id' => '', 'key' => '', 'start' => 16, 'lenght' => 16, 'type' => 'Q', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 3, 'variable_name' => 'latitude', 'description' => '', 'display_name' => '', 'variable_id' => '', 'key' => '', 'start' => 32, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 4, 'variable_name' => 'longitude', 'description' => '', 'display_name' => '', 'variable_id' => '', 'key' => '', 'start' => 40, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 5, 'variable_name' => 'flags', 'description' => '', 'display_name' => '', 'variable_id' => '', 'key' => '', 'start' => 48, 'lenght' => 16, 'type' => 'Q', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 6, 'variable_name' => 'timestamp', 'description' => '', 'display_name' => '', 'variable_id' => '', 'key' => '', 'start' => 64, 'lenght' => 8, 'type' => 'l', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 7, 'variable_name' => 'ph1_volt', 'description' => '', 'display_name' => 'L1 V', 'variable_id' => 17, 'key' => 'L1', 'start' => 72, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 8, 'variable_name' => 'ph2_volt', 'description' => '', 'display_name' => 'L2 V', 'variable_id' => 17, 'key' => 'L2', 'start' => 80, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 9, 'variable_name' => 'ph3_volt', 'description' => '', 'display_name' => 'L3 V', 'variable_id' => 17, 'key' => 'L3', 'start' => 88, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 10, 'variable_name' => 'ph1_current', 'description' => '', 'display_name' => 'L1 A', 'variable_id' => 18, 'key' => 'L1', 'start' => 96, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 11, 'variable_name' => 'ph2_current', 'description' => '', 'display_name' => 'L2 A', 'variable_id' => 18, 'key' => 'L2', 'start' => 104, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 12, 'variable_name' => 'ph3_current', 'description' => '', 'display_name' => 'L3 A', 'variable_id' => 18, 'key' => 'L3', 'start' => 112, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 13, 'variable_name' => 'ph1_power', 'description' => '', 'display_name' => 'L1 W', 'variable_id' => 19, 'key' => 'L1', 'start' => 120, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 14, 'variable_name' => 'ph2_power', 'description' => '', 'display_name' => 'L2 W', 'variable_id' => 19, 'key' => 'L2', 'start' => 128, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 15, 'variable_name' => 'ph3_power', 'description' => '', 'display_name' => 'L3 W', 'variable_id' => 19, 'key' => 'L3', 'start' => 136, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 16, 'variable_name' => 'ph1_VA', 'description' => '', 'display_name' => 'L1 VA', 'variable_id' => 20, 'key' => 'L1', 'start' => 144, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 17, 'variable_name' => 'ph2_VA', 'description' => '', 'display_name' => 'L2 VA', 'variable_id' => 20, 'key' => 'L2', 'start' => 152, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 18, 'variable_name' => 'ph3_VA', 'description' => '', 'display_name' => 'L3 VA', 'variable_id' => 20, 'key' => 'L3', 'start' => 160, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 19, 'variable_name' => 'ph1_VAr', 'description' => '', 'display_name' => 'L1 VAR', 'variable_id' => 21, 'key' => 'L1', 'start' => 168, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 20, 'variable_name' => 'ph2_VAr', 'description' => '', 'display_name' => 'l2 VAR', 'variable_id' => 21, 'key' => 'L2', 'start' => 176, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 21, 'variable_name' => 'ph3_VAr', 'description' => '', 'display_name' => 'L3 VAR', 'variable_id' => 21, 'key' => 'L3', 'start' => 184, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 22, 'variable_name' => 'ph1_power_factor', 'description' => '', 'display_name' => 'L1 FP', 'variable_id' => 22, 'key' => 'L1', 'start' => 192, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 23, 'variable_name' => 'ph2_power_factor', 'description' => '', 'display_name' => 'L2 FP', 'variable_id' => 22, 'key' => 'L2', 'start' => 200, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 24, 'variable_name' => 'ph3_power_factor', 'description' => '', 'display_name' => 'L3 FP', 'variable_id' => 22, 'key' => 'L3', 'start' => 208, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 25, 'variable_name' => 'ph1_phase_angle', 'description' => '', 'display_name' => 'L1 AF', 'variable_id' => 23, 'key' => 'L1', 'start' => 216, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 26, 'variable_name' => 'ph2_phase_angle', 'description' => '', 'display_name' => 'L2 AF', 'variable_id' => 23, 'key' => 'L2', 'start' => 224, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 27, 'variable_name' => 'ph3_phase_angle', 'description' => '', 'display_name' => 'L3 AF', 'variable_id' => 23, 'key' => 'L3', 'start' => 232, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 28, 'variable_name' => 'total_system_power', 'description' => '', 'display_name' => '', 'variable_id' => '', 'key' => '', 'start' => 240, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 29, 'variable_name' => 'total_system_var', 'description' => '', 'display_name' => '', 'variable_id' => '', 'key' => '', 'start' => 248, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 30, 'variable_name' => 'frequency', 'description' => '', 'display_name' => 'FRECUENCIA', 'variable_id' => 28, 'key' => 'Hz', 'start' => 256, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 31, 'variable_name' => 'import_wh', 'description' => '', 'display_name' => 'ENERGIA kWh TOTAL', 'variable_id' => 1, 'key' => 'TOTAL', 'start' => 264, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 32, 'variable_name' => 'export_wh', 'description' => '', 'display_name' => '', 'variable_id' => '', 'key' => '', 'start' => 272, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 33, 'variable_name' => 'import_VArh', 'description' => '', 'display_name' => 'ENERGIA kVARh TOTAL', 'variable_id' => 5, 'key' => 'TOTAL', 'start' => 280, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 34, 'variable_name' => 'export_VArh', 'description' => '', 'display_name' => '', 'variable_id' => '', 'key' => '', 'start' => 288, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 35, 'variable_name' => 'ph1_ph2_volt', 'description' => '', 'display_name' => 'L1-L2 V', 'variable_id' => 24, 'key' => 'L1-L2', 'start' => 296, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 36, 'variable_name' => 'ph2_ph3_volt', 'description' => '', 'display_name' => 'L2-L3 V', 'variable_id' => 24, 'key' => 'L2-L3', 'start' => 304, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 37, 'variable_name' => 'ph3_ph1_volt', 'description' => '', 'display_name' => 'L3-L4 V', 'variable_id' => 24, 'key' => 'L3-L1', 'start' => 312, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 38, 'variable_name' => 'ph1_volt_thd', 'description' => '', 'display_name' => 'L1 VTHD', 'variable_id' => 26, 'key' => 'L1', 'start' => 320, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 39, 'variable_name' => 'ph2_volt_thd', 'description' => '', 'display_name' => 'L2 VTHD', 'variable_id' => 26, 'key' => 'L2', 'start' => 328, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 40, 'variable_name' => 'ph3_volt_thd', 'description' => '', 'display_name' => 'L3 VTHD', 'variable_id' => 26, 'key' => 'L3', 'start' => 336, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 41, 'variable_name' => 'ph1_current_thd', 'description' => '', 'display_name' => 'L1 ATHD', 'variable_id' => 25, 'key' => 'L1', 'start' => 344, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 42, 'variable_name' => 'ph2_current_thd', 'description' => '', 'display_name' => 'L2 ATHD', 'variable_id' => 25, 'key' => 'L2', 'start' => 352, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 43, 'variable_name' => 'ph3_current_thd', 'description' => '', 'display_name' => 'L3 ATHD', 'variable_id' => 25, 'key' => 'L3', 'start' => 360, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 44, 'variable_name' => 'ph1_ph2_volt_thd', 'description' => '', 'display_name' => 'L1-L2 VTHD', 'variable_id' => 27, 'key' => 'L1-L2', 'start' => 368, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 45, 'variable_name' => 'ph2_ph3_volt_thd', 'description' => '', 'display_name' => 'L2-L3 VTHD', 'variable_id' => 27, 'key' => 'L2-L3', 'start' => 376, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 46, 'variable_name' => 'ph3_ph1_volt_thd', 'description' => '', 'display_name' => 'L3-L1 VTHD', 'variable_id' => 27, 'key' => 'L3-L1', 'start' => 384, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 47, 'variable_name' => 'ph1_import_kwh', 'description' => '', 'display_name' => 'L1 ENERGIA kWh TOTAL', 'variable_id' => 3, 'key' => 'L1', 'start' => 392, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 48, 'variable_name' => 'ph2_import_kwh', 'description' => '', 'display_name' => 'L2 ENERGIA kWh TOTAL', 'variable_id' => 3, 'key' => 'L2', 'start' => 400, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 49, 'variable_name' => 'ph3_import_kwh', 'description' => '', 'display_name' => 'L3 ENERGIA kWh TOTAL', 'variable_id' => 3, 'key' => 'L3', 'start' => 408, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 50, 'variable_name' => 'ph1_import_kvarh', 'description' => '', 'display_name' => 'L1 ENERGIA kVARh TOTAL', 'variable_id' => 7, 'key' => 'L1', 'start' => 416, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 51, 'variable_name' => 'ph2_import_kvarh', 'description' => '', 'display_name' => 'L2 ENERGIA kVARh TOTAL', 'variable_id' => 7, 'key' => 'L2', 'start' => 424, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 52, 'variable_name' => 'ph3_import_kvarh', 'description' => '', 'display_name' => 'L3 ENERGIA kVARh TOTAL', 'variable_id' => 7, 'key' => 'L3', 'start' => 432, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 53, 'variable_name' => 'ph1_varCh_acumm', 'description' => '', 'display_name' => 'L1 ENERGIA kVARCh TOTAL', 'variable_id' => 11, 'key' => 'L1', 'start' => 440, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 54, 'variable_name' => 'ph1_varLh_acumm', 'description' => '', 'display_name' => 'L1 ENERGIA kVARLh TOTAL', 'variable_id' => 15, 'key' => 'L1', 'start' => 448, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 55, 'variable_name' => 'ph2_varCh_acumm', 'description' => '', 'display_name' => 'L2 ENERGIA kVARCh TOTAL', 'variable_id' => 11, 'key' => 'L2', 'start' => 456, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 56, 'variable_name' => 'ph2_varLh_acumm', 'description' => '', 'display_name' => 'L2 ENERGIA kVARLh TOTAL', 'variable_id' => 15, 'key' => 'L2', 'start' => 464, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 57, 'variable_name' => 'ph3_varCh_acumm', 'description' => '', 'display_name' => 'L3 ENERGIA kVARCh TOTAL', 'variable_id' => 11, 'key' => 'L3', 'start' => 472, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 58, 'variable_name' => 'ph3_varLh_acumm', 'description' => '', 'display_name' => 'L3 ENERGIA kVARLh TOTAL', 'variable_id' => 15, 'key' => 'L3', 'start' => 480, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 59, 'variable_name' => 'Wh_calc', 'description' => '', 'display_name' => '', 'variable_id' => '', 'key' => '', 'start' => 488, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 60, 'variable_name' => 'ph1_varCh_interval', 'description' => '', 'display_name' => 'L1 ENERGIA kVARCh HORARIO', 'variable_id' => 12, 'key' => 'L1', 'start' => 496, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
        ['id' => 61, 'variable_name' => 'ph1_varLh_interval', 'description' => '', 'display_name' => 'L1 ENERGIA kVARLh HORARIO', 'variable_id' => 16, 'key' => 'L1', 'start' => 504, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
        ['id' => 62, 'variable_name' => 'ph2_varCh_interval', 'description' => '', 'display_name' => 'L2 ENERGIA kVARCh HORARIO', 'variable_id' => 12, 'key' => 'L2', 'start' => 512, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
        ['id' => 63, 'variable_name' => 'ph2_varLh_interval', 'description' => '', 'display_name' => 'L2 ENERGIA kVARLh HORARIO', 'variable_id' => 16, 'key' => 'L2', 'start' => 520, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
        ['id' => 64, 'variable_name' => 'ph3_varCh_interval', 'description' => '', 'display_name' => 'L3 ENERGIA kVARCh HORARIO', 'variable_id' => 12, 'key' => 'L3', 'start' => 528, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
        ['id' => 65, 'variable_name' => 'ph3_varLh_interval', 'description' => '', 'display_name' => 'L3 ENERGIA kVARLh HORARIO', 'variable_id' => 16, 'key' => 'L3', 'start' => 536, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
        ['id' => 66, 'variable_name' => 'varLh_acumm', 'description' => '', 'display_name' => 'ENERGIA kVARLh TOTAL', 'variable_id' => 13, 'key' => 'TOTAL', 'start' => 544, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 67, 'variable_name' => 'varCh_acumm', 'description' => '', 'display_name' => 'ENERGIA kVARCh TOTAL', 'variable_id' => 9, 'key' => 'TOTAL', 'start' => 552, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => false],
        ['id' => 68, 'variable_name' => 'kwh_interval', 'description' => '', 'display_name' => 'ENERGIA kWh HORARIO', 'variable_id' => 2, 'key' => 'TOTAL', 'start' => 568, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
        ['id' => 69, 'variable_name' => 'varLh_interval', 'description' => '', 'display_name' => 'ENERGIA kVARLh HORARIO', 'variable_id' => 14, 'key' => 'TOTAL', 'start' => 560, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
        ['id' => 70, 'variable_name' => 'varCh_interval', 'description' => '', 'display_name' => 'ENERGIA kVARCh HORARIO', 'variable_id' => 10, 'key' => 'TOTAL', 'start' => 568, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
        ['id' => 71, 'variable_name' => 'ph1_kwh_interval', 'description' => '', 'display_name' => 'L1 ENERGIA kWh HORARIO', 'variable_id' => 4, 'key' => 'L1', 'start' => 568, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
        ['id' => 72, 'variable_name' => 'ph2_kwh_interval', 'description' => '', 'display_name' => 'L2 ENERGIA kWh HORARIO', 'variable_id' => 4, 'key' => 'L2', 'start' => 568, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
        ['id' => 73, 'variable_name' => 'ph3_kwh_interval', 'description' => '', 'display_name' => 'L3 ENERGIA kWh HORARIO', 'variable_id' => 4, 'key' => 'L3', 'start' => 568, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
        ['id' => 74, 'variable_name' => 'varh_interval', 'description' => '', 'display_name' => 'ENERGIA kVARh HORARIO', 'variable_id' => 6, 'key' => 'TOTAL', 'start' => 568, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
        ['id' => 75, 'variable_name' => 'ph1_varh_interval', 'description' => '', 'display_name' => 'L1 ENERGIA kVARh HORARIO', 'variable_id' => 8, 'key' => 'L1', 'start' => 568, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
        ['id' => 76, 'variable_name' => 'ph2_varh_interval', 'description' => '', 'display_name' => 'L2 ENERGIA kVARh HORARIO', 'variable_id' => 8, 'key' => 'L2', 'start' => 568, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
        ['id' => 77, 'variable_name' => 'ph3_varh_interval', 'description' => '', 'display_name' => 'L3 ENERGIA kVARh HORARIO', 'variable_id' => 8, 'key' => 'L3', 'start' => 568, 'lenght' => 8, 'type' => 'f', 'factor' => 1, 'bolean_accum' => true],
    ],

    'alert_config_frame' => [
        ['variable_name' => 'network_operator_id', 'start' => 0, 'lenght' => 16, 'type' => 'Q'],
        ['variable_name' => 'equipment_id', 'start' => 16, 'lenght' => 16, 'type' => 'Q'],
        ['variable_name' => 'network_operator_new_id', 'start' => 32, 'lenght' => 16, 'type' => 'Q'],
        ['variable_name' => 'equipment_new_id', 'start' => 48, 'lenght' => 16, 'type' => 'Q'],
        ['flag_id' => 16, 'limit' => 'max_alert', 'variable_name' => 'max_vol_ph_1', 'start' => 64, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 16, 'limit' => 'min_alert', 'variable_name' => 'min_vol_ph_1', 'start' => 72, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 17, 'limit' => 'max_alert', 'variable_name' => 'max_vol_ph_2', 'start' => 80, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 17, 'limit' => 'min_alert', 'variable_name' => 'min_vol_ph_2', 'start' => 88, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 18, 'limit' => 'max_alert', 'variable_name' => 'max_vol_ph_3', 'start' => 96, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 18, 'limit' => 'min_alert', 'variable_name' => 'min_vol_ph_3', 'start' => 104, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 19, 'limit' => 'max_alert', 'variable_name' => 'max_current_ph_1', 'start' => 112, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 19, 'limit' => 'min_alert', 'variable_name' => 'min_current_ph_1', 'start' => 120, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 20, 'limit' => 'max_alert', 'variable_name' => 'max_current_ph_2', 'start' => 128, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 20, 'limit' => 'min_alert', 'variable_name' => 'min_current_ph_2', 'start' => 136, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 21, 'limit' => 'max_alert', 'variable_name' => 'max_current_ph_3', 'start' => 144, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 21, 'limit' => 'min_alert', 'variable_name' => 'min_current_ph_3', 'start' => 152, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 22, 'limit' => 'max_alert', 'variable_name' => 'max_power_ph_1', 'start' => 160, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 22, 'limit' => 'min_alert', 'variable_name' => 'min_power_ph_1', 'start' => 168, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 23, 'limit' => 'max_alert', 'variable_name' => 'max_power_ph_2', 'start' => 176, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 23, 'limit' => 'min_alert', 'variable_name' => 'min_power_ph_2', 'start' => 184, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 24, 'limit' => 'max_alert', 'variable_name' => 'max_power_ph_3', 'start' => 192, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 24, 'limit' => 'min_alert', 'variable_name' => 'min_power_ph_3', 'start' => 200, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 25, 'limit' => 'max_alert', 'variable_name' => 'max_va_ph_1', 'start' => 208, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 25, 'limit' => 'min_alert', 'variable_name' => 'min_va_ph_1', 'start' => 216, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 26, 'limit' => 'max_alert', 'variable_name' => 'max_va_ph_2', 'start' => 224, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 26, 'limit' => 'min_alert', 'variable_name' => 'min_va_ph_2', 'start' => 232, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 27, 'limit' => 'max_alert', 'variable_name' => 'max_va_ph_3', 'start' => 240, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 27, 'limit' => 'min_alert', 'variable_name' => 'min_va_ph_3', 'start' => 248, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 28, 'limit' => 'max_alert', 'variable_name' => 'max_var_ph_1', 'start' => 256, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 28, 'limit' => 'min_alert', 'variable_name' => 'min_var_ph_1', 'start' => 264, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 29, 'limit' => 'max_alert', 'variable_name' => 'max_var_ph_2', 'start' => 272, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 29, 'limit' => 'min_alert', 'variable_name' => 'min_var_ph_2', 'start' => 280, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 30, 'limit' => 'max_alert', 'variable_name' => 'max_var_ph_3', 'start' => 288, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 30, 'limit' => 'min_alert', 'variable_name' => 'min_var_ph_3', 'start' => 296, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 31, 'limit' => 'max_alert', 'variable_name' => 'max_pfp_ph_1', 'start' => 304, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 31, 'limit' => 'min_alert', 'variable_name' => 'min_pfp_ph_1', 'start' => 312, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 32, 'limit' => 'max_alert', 'variable_name' => 'max_pfp_ph_2', 'start' => 320, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 32, 'limit' => 'min_alert', 'variable_name' => 'min_pfp_ph_2', 'start' => 328, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 33, 'limit' => 'max_alert', 'variable_name' => 'max_pfp_ph_3', 'start' => 336, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 33, 'limit' => 'min_alert', 'variable_name' => 'min_pfp_ph_3', 'start' => 344, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 34, 'limit' => 'max_alert', 'variable_name' => 'max_freq', 'start' => 352, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 34, 'limit' => 'min_alert', 'variable_name' => 'min_freq', 'start' => 360, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 35, 'limit' => 'max_alert', 'variable_name' => 'max_volt_1_2', 'start' => 368, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 35, 'limit' => 'min_alert', 'variable_name' => 'min_volt_1_2', 'start' => 376, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 37, 'limit' => 'max_alert', 'variable_name' => 'max_volt_3_1', 'start' => 384, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 37, 'limit' => 'min_alert', 'variable_name' => 'min_volt_3_1', 'start' => 392, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 36, 'limit' => 'max_alert', 'variable_name' => 'max_volt_2_3', 'start' => 400, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 36, 'limit' => 'min_alert', 'variable_name' => 'min_volt_2_3', 'start' => 408, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 38, 'limit' => 'max_alert', 'variable_name' => 'max_vthd_ph_1', 'start' => 416, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 38, 'limit' => 'min_alert', 'variable_name' => 'min_vthd_ph_1', 'start' => 424, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 39, 'limit' => 'max_alert', 'variable_name' => 'max_vthd_ph_2', 'start' => 432, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 39, 'limit' => 'min_alert', 'variable_name' => 'min_vthd_ph_2', 'start' => 440, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 40, 'limit' => 'max_alert', 'variable_name' => 'max_vthd_ph_3', 'start' => 448, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 40, 'limit' => 'min_alert', 'variable_name' => 'min_vthd_ph_3', 'start' => 456, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 41, 'limit' => 'max_alert', 'variable_name' => 'max_cthd_ph_1', 'start' => 464, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 41, 'limit' => 'min_alert', 'variable_name' => 'min_cthd_ph_1', 'start' => 472, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 42, 'limit' => 'max_alert', 'variable_name' => 'max_cthd_ph_2', 'start' => 480, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 42, 'limit' => 'min_alert', 'variable_name' => 'min_cthd_ph_2', 'start' => 488, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 43, 'limit' => 'max_alert', 'variable_name' => 'max_cthd_ph_3', 'start' => 496, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 43, 'limit' => 'min_alert', 'variable_name' => 'min_cthd_ph_3', 'start' => 504, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 44, 'limit' => 'max_alert', 'variable_name' => 'max_vthd_ph_1_2', 'start' => 512, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 44, 'limit' => 'min_alert', 'variable_name' => 'min_vthd_ph_1_2', 'start' => 520, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 45, 'limit' => 'max_alert', 'variable_name' => 'max_vthd_ph_2_3', 'start' => 528, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 45, 'limit' => 'min_alert', 'variable_name' => 'min_vthd_ph_2_3', 'start' => 536, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 46, 'limit' => 'max_alert', 'variable_name' => 'max_vthd_ph_3_1', 'start' => 544, 'lenght' => 8, 'type' => 'f'],
        ['flag_id' => 46, 'limit' => 'min_alert', 'variable_name' => 'min_vthd_ph_3_1', 'start' => 552, 'lenght' => 8, 'type' => 'f'],

    ],

    'flags_frame' => [
        ['id' => 1, 'flag_name' => 'flagStorage', 'description' => '', 'bit' => 0, 'index' => 59],
        ['id' => 2, 'flag_name' => 'flagAlert', 'description' => '', 'bit' => 1, 'index' => 58],
        ['id' => 3, 'flag_name' => 'flagIsWifi', 'description' => '', 'bit' => 2, 'index' => 57],
        ['id' => 4, 'flag_name' => 'coil1', 'description' => '', 'bit' => 3, 'index' => 56],
        ['id' => 5, 'flag_name' => 'coil2', 'description' => '', 'bit' => 4, 'index' => 55],
        ['id' => 6, 'flag_name' => 'coil3', 'description' => '', 'bit' => 5, 'index' => 54],
        ['id' => 7, 'flag_name' => 'coil4', 'description' => '', 'bit' => 6, 'index' => 53],
        ['id' => 8, 'flag_name' => 'coil5', 'description' => '', 'bit' => 7, 'index' => 52],
        ['id' => 9, 'flag_name' => 'coil6', 'description' => '', 'bit' => 8, 'index' => 51],
        ['id' => 10, 'flag_name' => 'coil7', 'description' => '', 'bit' => 9, 'index' => 50],
        ['id' => 11, 'flag_name' => 'coil8', 'description' => '', 'bit' => 10, 'index' => 49],
        ['id' => 12, 'flag_name' => 'coil9', 'description' => '', 'bit' => 11, 'index' => 48],
        ['id' => 13, 'flag_name' => 'coil10', 'description' => '', 'bit' => 12, 'index' => 47],
        ['id' => 14, 'flag_name' => 'flagOpened', 'description' => '', 'bit' => 27, 'index' => 32],
        ['id' => 15, 'flag_name' => 'flagAdc1', 'description' => '', 'bit' => 28, 'index' => 31],
        ['id' => 16, 'flag_name' => 'flagVolt1', 'description' => '', 'variable_name' => 'ph1_volt', 'placeholder' => 'Voltaje fase 1', 'bit' => 29, 'index' => 30, 'variable_id' => 7],
        ['id' => 17, 'flag_name' => 'flagVolt2', 'description' => '', 'variable_name' => 'ph2_volt', 'placeholder' => 'Voltaje fase 2', 'bit' => 30, 'index' => 29, 'variable_id' => 8],
        ['id' => 18, 'flag_name' => 'flagVolt3', 'description' => '', 'variable_name' => 'ph3_volt', 'placeholder' => 'Voltaje fase 3', 'bit' => 31, 'index' => 28, 'variable_id' => 9],
        ['id' => 19, 'flag_name' => 'flagCurr1', 'description' => '', 'variable_name' => 'ph1_current', 'placeholder' => 'Corriente fase 1', 'bit' => 32, 'index' => 27, 'variable_id' => 10],
        ['id' => 20, 'flag_name' => 'flagCurr2', 'description' => '', 'variable_name' => 'ph2_current', 'placeholder' => 'Corriente fase 2', 'bit' => 33, 'index' => 26, 'variable_id' => 11],
        ['id' => 21, 'flag_name' => 'flagCurr3', 'description' => '', 'variable_name' => 'ph3_current', 'placeholder' => 'Corriente fase 3', 'bit' => 34, 'index' => 25, 'variable_id' => 12],
        ['id' => 22, 'flag_name' => 'flagPot1', 'description' => '', 'variable_name' => 'ph1_power', 'placeholder' => 'Potencia fase 1', 'bit' => 35, 'index' => 24, 'variable_id' => 13],
        ['id' => 23, 'flag_name' => 'flagPot2', 'description' => '', 'variable_name' => 'ph2_power', 'placeholder' => 'Potencia fase 2', 'bit' => 36, 'index' => 23, 'variable_id' => 14],
        ['id' => 24, 'flag_name' => 'flagPot3', 'description' => '', 'variable_name' => 'ph3_power', 'placeholder' => 'Potencia fase 3', 'bit' => 37, 'index' => 22, 'variable_id' => 15],
        ['id' => 25, 'flag_name' => 'flagVA1', 'description' => '', 'variable_name' => 'ph1_VA', 'placeholder' => 'Voltio-Amperios fase 1', 'bit' => 38, 'index' => 21, 'variable_id' => 16],
        ['id' => 26, 'flag_name' => 'flagVA2', 'description' => '', 'variable_name' => 'ph2_VA', 'placeholder' => 'Voltio-Amperios fase 2', 'bit' => 39, 'index' => 20, 'variable_id' => 17],
        ['id' => 27, 'flag_name' => 'flagVA3', 'description' => '', 'variable_name' => 'ph3_VA', 'placeholder' => 'Voltio-Amperios fase 3', 'bit' => 40, 'index' => 19, 'variable_id' => 18],
        ['id' => 28, 'flag_name' => 'flagVAr1', 'description' => '', 'variable_name' => 'ph1_VAr', 'placeholder' => 'Voltio-Amperios reactivos fase 1', 'bit' => 41, 'index' => 18, 'variable_id' => 19],
        ['id' => 29, 'flag_name' => 'flagVAr2', 'description' => '', 'variable_name' => 'ph2_VAr', 'placeholder' => 'Voltio-Amperios reactivos fase 2', 'bit' => 42, 'index' => 17, 'variable_id' => 20],
        ['id' => 30, 'flag_name' => 'flagVAr3', 'description' => '', 'variable_name' => 'ph3_VAr', 'placeholder' => 'Voltio-Amperios reactivos fase 3', 'bit' => 43, 'index' => 16, 'variable_id' => 21],
        ['id' => 31, 'flag_name' => 'flagPF1', 'description' => '', 'variable_name' => 'ph1_power_factor', 'placeholder' => 'Factor de potenci fase 1', 'bit' => 44, 'index' => 15, 'variable_id' => 22],
        ['id' => 32, 'flag_name' => 'flagPF2', 'description' => '', 'variable_name' => 'ph2_power_factor', 'placeholder' => 'Factor de potenci fase 2', 'bit' => 45, 'index' => 14, 'variable_id' => 23],
        ['id' => 33, 'flag_name' => 'flagPF3', 'description' => '', 'variable_name' => 'ph3_power_factor', 'placeholder' => 'Factor de potenci fase 3', 'bit' => 46, 'index' => 13, 'variable_id' => 24],
        ['id' => 34, 'flag_name' => 'flag_Freq', 'description' => '', 'variable_name' => 'frequency', 'placeholder' => 'Frecuencia', 'bit' => 47, 'index' => 12, 'variable_id' => 30],
        ['id' => 35, 'flag_name' => 'flagVolt12', 'description' => '', 'variable_name' => 'ph1_ph2_volt', 'placeholder' => 'Voltaje entre fase 1 y 2', 'bit' => 48, 'index' => 11, 'variable_id' => 35],
        ['id' => 36, 'flag_name' => 'flagVolt23', 'description' => '', 'variable_name' => 'ph2_ph3_volt', 'placeholder' => 'Voltaje entre fase 2 y 3', 'bit' => 49, 'index' => 10, 'variable_id' => 36],
        ['id' => 37, 'flag_name' => 'flagVolt31', 'description' => '', 'variable_name' => 'ph3_ph1_volt', 'placeholder' => 'Voltaje entre fase 3 y 1', 'bit' => 50, 'index' => 9, 'variable_id' => 37],
        ['id' => 38, 'flag_name' => 'flagTHDVolt1', 'description' => '', 'variable_name' => 'ph1_volt_thd', 'placeholder' => 'Distorsion armonica total voltaje fase 1', 'bit' => 51, 'index' => 8, 'variable_id' => 38],
        ['id' => 39, 'flag_name' => 'flagTHDVolt2', 'description' => '', 'variable_name' => 'ph2_volt_thd', 'placeholder' => 'Distorsion armonica total voltaje fase 2', 'bit' => 52, 'index' => 7, 'variable_id' => 39],
        ['id' => 40, 'flag_name' => 'flagTHDVolt3', 'description' => '', 'variable_name' => 'ph3_volt_thd', 'placeholder' => 'Distorsion armonica total voltaje fase 3', 'bit' => 53, 'index' => 6, 'variable_id' => 40],
        ['id' => 41, 'flag_name' => 'flagTHDCurr1', 'description' => '', 'variable_name' => 'ph1_current_thd', 'placeholder' => 'Distorsion armonica total corriente fase 1', 'bit' => 54, 'index' => 5, 'variable_id' => 41],
        ['id' => 42, 'flag_name' => 'flagTHDCurr2', 'description' => '', 'variable_name' => 'ph2_current_thd', 'placeholder' => 'Distorsion armonica total corriente fase 2', 'bit' => 55, 'index' => 4, 'variable_id' => 42],
        ['id' => 43, 'flag_name' => 'flagTHDCurr3', 'description' => '', 'variable_name' => 'ph3_current_thd', 'placeholder' => 'Distorsion armonica total corriente fase 3', 'bit' => 56, 'index' => 3, 'variable_id' => 43],
        ['id' => 44, 'flag_name' => 'flagTHDVolt12', 'description' => '', 'variable_name' => 'ph1_ph2_volt_thd', 'placeholder' => 'Distorsion armonica total voltaje entre fase 1 y 2', 'bit' => 57, 'index' => 2, 'variable_id' => 44],
        ['id' => 45, 'flag_name' => 'flagTHDVolt23', 'description' => '', 'variable_name' => 'ph2_ph3_volt_thd', 'placeholder' => 'Distorsion armonica total voltaje entre fase 2 y 3', 'bit' => 58, 'index' => 1, 'variable_id' => 45],
        ['id' => 46, 'flag_name' => 'flagTHDVolt31', 'description' => '', 'variable_name' => 'ph3_ph1_volt_thd', 'placeholder' => 'Distorsion armonica total voltaje entre fase 3 y 1', 'bit' => 59, 'index' => 0, 'variable_id' => 46],
        ['id' => 47, 'flag_name' => 'kwh_month', 'placeholder' => 'kWh/Mes'],
        ['id' => 48, 'flag_name' => 'kvarlh_month', 'placeholder' => 'kVARLh/Mes'],
        ['id' => 49, 'flag_name' => 'kvarch_month', 'placeholder' => 'kVARCh/Mes'],
        ['id' => 50, 'flag_name' => 'kwh_hour', 'placeholder' => 'kWh/Hora'],
        ['id' => 51, 'flag_name' => 'kvarlh_hour', 'placeholder' => 'kVARLh/Hora'],
        ['id' => 52, 'flag_name' => 'kvarch_hour', 'placeholder' => 'kVARCh/Hora'],
        ['id' => 53, 'flag_name' => 'kvarlh_penalizable', 'placeholder' => 'Porcentaje horario kVARLh/kWh'],
    ]

];
